### ISSUE TITLE
nex nostalgia plugin very loud

### ISSUE THREAD

**Issue by zhedax** [hex-agon/runelite-plugins#1]
Hey! Maybe you could remove the cap of -10 in nex nostalgia plugin? It is still very loud for me and my in game sounds are only set to 2%. Or maybe do you have any other solutions, maybe its a bug? Some streamers say they have similar sound settings and its not that loud for them.

**Comment by hex-agon** [comment]
I've updated the plugin to allow volume reduction up to -25 db.
