### ISSUE TITLE
[nex-nostalgia] Issue with the new update

### ISSUE THREAD

**Issue by jonathanCioanca** [hex-agon/runelite-plugins#2]
there seems to be an issue with the new update where the sounds dont work at all. not sure what exactly is the root of the issue but it started after patch

**Comment by jonathanCioanca** [comment]
Accidentally closed the issue my mistake

**Comment by hex-agon** [comment]
jagex added a new chattype for npc voice overs which means this return is now being reached: https://github.com/hex-agon/runelite-plugins/blob/nex-nostalgia/src/main/java/work/fking/nexnostalgia/NexNostalgiaPlugin.java#L100

i'll update once we get the new chattype in runelite

**Comment by sleepyhauru** [comment]
https://github.com/runelite/runelite/pull/18027
It looks like commit request to add the chattype has been approved.

**Comment by hex-agon** [comment]
Fixed in c81095b0b357b380e7894ee5baf4611044456884

Waiting for the next runelite release
https://github.com/runelite/plugin-hub/pull/6278

**Comment by cs91osrs** [comment]
still occouring even though marked as complete

**Comment by Dhabss** [comment]
Sounds dont work, tried reinstalling runelite and the plug in. nothing changes.

**Comment by sleepyhauru** [comment]
@cs91osrs @Dhabss Runelite update hasn't gone through yet.
If you click the plugin hub link from creator, it shows tagged as "Hold for release"
